### ISSUE TITLE
Valid alias characters upon generating alias

### ISSUE THREAD

**Issue by daniel-nemeth** [MetaModels/attribute_translatedalias#19]
Hi guys.
Just a short question to the translated alias attribute.
Is the alias generation according to the settings from contao root page (ascii or unicode)?

I have a de/en page and for both i have set the alias to ascii & lowercase letters. But when the attribute generates the alias for german page, it still uses the unicode äöü.

I am running the latest Contao and MM versions.

Do i miss some settings?

Cheers!

**Comment by zonky2** [comment]
see https://metamodels.readthedocs.io/en/latest/manual/install.html#installing-mm-2-1

Contao 4.4 has no setting for alias
