### ISSUE TITLE
Alias not saved in tl_metamodel_translatedtext

### ISSUE THREAD

**Issue by Teetrinker** [MetaModels/attribute_translatedalias#7]
When the alias is not changed in the secondary languages, it will not be inserted into `tl_metamodel_translatedtext`.
When I edit another language and save it, the alias of this language is not inserted into `tl_metamodel_translatedtext` if it is still the same as in the first language.
When I change the alias of the second language, it is saved, when I change it back to be identical with the alias of the first language, it is saved as well.

This is not really a bug, more a mild inconsistency.

However, it complicates third party development, for example solutions for the combination of MM and [changelanguage]. Therefore, I suggest that aliases are always saved into `tl_metamodel_translatedtext`, even if identical.

See also the forum discussion: https://community.contao.org/de/showthread.php?45678-3-1-x-MM-mit-Sprachwechsler-funktioniert-nicht

**Comment by amenk** [comment]
I am trying to put that into a module...

**Comment by amenk** [comment]
https://github.com/iMi-digital/imi_mm_changelanguage

**Comment by xantippe** [comment]
@Teetrinker kann das Ticket damit geschlossen werden oder noch aktuell?

**Comment by discordier** [comment]
contao-community-alliance/dc-general#174
