### ISSUE TITLE
Filter: "Simple lookup" does not resolve Attribute translatedalias correct

### ISSUE THREAD

**Issue by Teetrinker** [MetaModels/attribute_translatedalias#9]
Setup:
- MM nightly build 2014-11-26
- Filter: "Simple lookup", Attribute: translatedalias
- Problem: The filter does not return objects if the set language is not the main language, but the alias is the same as in the main language.
  (Ergo the alias is not present in the database table `tl_metamodel_translatedtext`.)

**Comment by discordier** [comment]
This is either a generic issue still present in `MetaModels\Attribute\TranslatedReference` or has been resolved already. @zonky2 can you test?

This is the remaining holdup for 2.0.0 stable.

**Comment by zonky2** [comment]
Hm... I`m not shure how can I check this...

**Comment by discordier** [comment]
Let's discuss this on mumble.

**Comment by zonky2** [comment]
look at https://github.com/MetaModels/core/issues/1092
